=== McPhp/Lab7/data/schedule.dtd
<!-- schedule constraints -->
<!ELEMENT schedule (info, courses, days, timeslots)>
<!ELEMENT info (program, year, term, set)>
<!ELEMENT program (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT set (#PCDATA)>


<!-- booking constraints -->
<!ELEMENT booking (building, room, instructor)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT instructor (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ATTLIST booking
	type (Lecture|Lab) #REQUIRED
	start (8:30am|9:30am|10:30am|11:30am|12:30pm|1:30pm|2:30pm|3:30pm|4:30pm) #IMPLIED
	end (9:20am|10:20am|11:20am|12:20pm|1:20pm|2:20pm|3:20pm|4:20pm|5:20pm) #IMPLIED
	course (BLAW3600|COMP4560|COMP4711|COMP4735|COMP4900|COMP4941|COMP4945) #IMPLIED
	day (Monday|Tuesday|Wednesday|Thursday|Friday) #IMPLIED
>


<!-- courses constraints -->
<!ELEMENT courses (course+)>
<!ELEMENT course (booking+)>
<!ATTLIST course
	name (COMP|BLAW) #REQUIRED
	number (3600|4560|4711|4735|4900|4941|4945) #REQUIRED
>



<!-- days constraints -->
<!ELEMENT days (day+)>
<!ELEMENT day (booking+)>
<!ATTLIST day
	day_of_the_week (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>


<!-- timeslots constraints -->
<!ELEMENT timeslots (hour+)>
<!ELEMENT hour (booking+)>
<!ATTLIST hour
	start (8:30am|9:30am|10:30am|11:30am|12:30pm|1:30pm|2:30pm|3:30pm|4:30pm) #REQUIRED
>

=== McPhp/Lab7/data/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "schedule.dtd">

<schedule>
	<info>
		<program>CST</program>
		<year>2016</year>
		<term>4</term>
		<set>G</set>
	</info>
	
	<!-- Courses -->
	<courses>
		<course name="COMP" number="4711">
			<booking type="Lecture" start="8:30am" end="9:20am" day="Monday">
				<building>SW5</building>
				<room>1850</room>
				<instructor>
					<firstname>Jim</firstname>
					<lastname>Parry</lastname>
				</instructor>
			</booking>
			
			<booking type="Lab" start="12:30pm" end="2:20pm" day="Tuesday">
				<building>SE12</building>
				<room>320</room>
				<instructor>
					<firstname>Jim</firstname>
					<lastname>Parry</lastname>
				</instructor>
			</booking>
		</course>
		
	</courses>

	<!-- Daysoftheweek -->
	<days>
		<day day_of_the_week = "Monday">
			<booking type="Lecture" start="8:30am" end="9:20am" course="COMP4711">
				<building>SW5</building>
				<room>1850</room>
				<instructor>
					<firstname>Jim</firstname>
					<lastname>Parry</lastname>
				</instructor>
			</booking>

			<booking type="Lecture" start="4:30pm" end="5:20pm" course="COMP4711">
				<building>SW5</building>
				<room>1851</room>
				<instructor>
					<firstname>Bernie</firstname>
					<lastname>Sanders</lastname>
				</instructor>
			</booking>
		</day>
	</days>

	<!-- timeslots -->
	<timeslots>
		<hour start="8:30am">
			<booking type="Lecture" course="COMP4711" day="Monday">
				<building>SW5</building>
				<room>1850</room>
				<instructor>
					<firstname>Jim</firstname>
					<lastname>Parry</lastname>
				</instructor>
			</booking>
			<booking type="Lecture" course="COMP4711" day="Tuesday">
				<building>SW5</building>
				<room>1851</room>
				<instructor>
					<firstname>Paul</firstname>
					<lastname>John</lastname>
				</instructor>
			</booking>
		</hour>
	</timeslots>
	
</schedule>
